it is possible to setup the github dir

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -20,22 +20,26 @@ if [ -z "${NECROCONF_URL}" ]; then
     NECROCONF_URL=https://github.com/fredericorecsky/configs.git
 fi
 
-GITHUBDIR=~/github
+if [ -z "${GITHUBDIR}" ];then
+    GITHUBDIR=~/github
+fi
+
 if [ ! -d $GITHUBDIR ];then
     mkdir -p $GITHUBDIR
 fi
 
 cd $GITHUBDIR
 if [ $? -eq 0 ];then 
-    git clone $NECROCONF_URL
-    if [ $? ];then
-        echo "could not clone $NECROCONF_URL"
-        echo "verify your internet connection settings"
-        exit 1;
+    if [ ! -d "configs" ];then 
+        git clone $NECROCONF_URL
+        if [ $? -ne 0 ];then
+            echo "could not clone $NECROCONF_URL"
+            echo "verify your internet connection settings"
+            exit 1;
+        fi
     fi
     cd configs
-    echo "Run bashrc"
-    #bash bashrc/bashrc
+    sh bashrc/bashrc
 else
     echo "Could not change to github dir"
     exit 1;
